### ISSUE TITLE
display_flash_messages return nil on redirection

### ISSUE THREAD

**Issue by Sohair63** [sgruhier/foundation_rails_helper#175]
This is the problem that I start facing of HTML request Format. 
After `redirect_to some_path, notice: 'some message'` UI does not show any alert or notice.

NOTE THAT: I have tried `flash.now` `flash.keep` and `flash[:notice]`, nothing helped me.

I am Using:

- Rails 5.1.1
- foundation-rails 6.3.1.0
- foundation_rails_helper 3.0.0.rc2 from https://github.com/sgruhier/foundation_rails_helper.git (at master@3863808)

**Comment by dsandstrom** [comment]
I can't reproduce so I have some follow questions:

1. Do you have `<%= display_flash_messages %>` in your layout file?
2. If so, view the browser source and look for a ` <div class="flash callout success" data-closable="">` tag after redirecting.
3. If not there, does it work with foundation 6.2?

**Comment by Sohair63** [comment]
Yes 
1. I have that.
2. Yes this is there.
3. I am already using foundation 6

**Comment by dsandstrom** [comment]
Is the html for the flash notice in the source after a redirect?  If so, it sounds like this gem is doing it's job.  It may be a css issue then.  Am I misunderstanding something?

The reason I ask about 6.2/6.3 is because I haven't upgraded any apps to Foundation 6.3, so I'm not sure if there is an issue with that, but I doubt it.

**Comment by dsandstrom** [comment]
Going to close this since the lack of response.  If this is still an issue, please provide an example project that I can reproduce the problem on.
