### ISSUE TITLE
Allow configuration of text_field default behavior or disable helper on some forms

### ISSUE THREAD

**Issue by collimarco** [sgruhier/foundation_rails_helper#91]
I like this helper, but I don't think that forcing `f.text_field`to produce the label by default is always good.

I am forced to add the option `label: false`to a lot of labels.

Another option, even better, would be to allow to disable the entire custom helper on some forms. For example when I want to use the normal rails helper (not the modified version provided by this gem) I can write:

`form_for @example, {foundation_rails_helper: false}`

Or maybe do not override `form_for`but add a `form_with_helper_for`.

**Comment by dgmstuart** [comment]
These are great ideas, but I feel like they're feature requests - would you agree? Pull requests are very welcome :)

The first one should be implemented using the new [`Configuration` class](https://github.com/sgruhier/foundation_rails_helper/blob/45035047e515bd59aee428da9704cb33547559b2/lib/foundation_rails_helper/configuration.rb). This would allow users to configure their preferred default behaviour in an initialiser.

I'm not sure how you'd go about doing the latter.  I'd favour the {foundation_rails_helper: false} option, since this would let the helper continue to be fairly unobtrusive.

**Comment by dsandstrom** [comment]
Add the option `auto_labels: false` to the `form_for` method.  It should be what you are looking for.  Sorry, it's not documented.

**Comment by collimarco** [comment]
Thank you very much!

Maybe it should be added to the documentation because it's a useful feature :)

**Comment by dsandstrom** [comment]
Yes.  I'll keep this open to remind me.

**Comment by dgmstuart** [comment]
@dsandstrom also worth adding to the Configuration class if it's easy to do so

**Comment by dsandstrom** [comment]
I don't think this is a good fit for a configuration option.  If one wants to disable labels for all forms, there isn't much point in using this gem.
